# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-eradicate
          - flake8-executable
          - flake8-logging-format
          - flake8-mutable
          - flake8-print
          - flake8-return
          - flake8-self
          - pep8-naming
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.1.0
    hooks:
      - id: eslint
        args: ["--format=compact"]
        additional_dependencies:
          - prettier@latest
          - eslint@>=6.2.2
          - eslint-plugin-import@>=2.18.0
          - eslint-plugin-node@>=9.1.0
          - eslint-plugin-promise@>=4.2.1
          - eslint-plugin-standard@>=4.0.0
          - eslint-config-prettier@latest
          - eslint-plugin-prettier@latest
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        args: ["--formatter=compact"]
        additional_dependencies:
          - stylelint@latest
          - stylelint-config-prettier@latest
          - stylelint-prettier@latest
          - prettier@latest
